### ISSUE TITLE
"npm run coverage" does not work out of the box

### ISSUE THREAD

**Issue by pearcemerritt** [jazz-soft/JZZ-midi-SMF#3]
I cloned this project yesterday. To get it up an running today I did: `npm i` and then tried the scripts in `package.json`. The first two (`test` and `lint`) worked. But when I tried to run `coverage` I got an error.

I'm guessing it's a simple piece missing from my local set-up that's not accounted for in the script, but I don't know what the expected behavior is, so I thought I'd just open this here for a rainy day.

Error:
```
$ npm run coverage

> jzz-midi-smf@1.2.4 coverage /Users/pearcemerritt/dev/JZZ-midi-SMF
> nyc report --reporter=text-lcov | coveralls


/Users/pearcemerritt/dev/JZZ-midi-SMF/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jzz-midi-smf@1.2.4 coverage: `nyc report --reporter=text-lcov | coveralls`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jzz-midi-smf@1.2.4 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pearcemerritt/.npm/_logs/2019-07-09T18_37_44_989Z-debug.log
```

`/Users/pearcemerritt/.npm/_logs/2019-07-09T18_37_44_989Z-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'coverage'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.1.0
4 verbose run-script [ 'precoverage', 'coverage', 'postcoverage' ]
5 info lifecycle jzz-midi-smf@1.2.4~precoverage: jzz-midi-smf@1.2.4
6 info lifecycle jzz-midi-smf@1.2.4~coverage: jzz-midi-smf@1.2.4
7 verbose lifecycle jzz-midi-smf@1.2.4~coverage: unsafe-perm in lifecycle true
8 verbose lifecycle jzz-midi-smf@1.2.4~coverage: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pearcemerritt/dev/JZZ-midi-SMF/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/dev/bin:/Users/pearcemerritt/Library/Android/sdk/emulator:/Users/pearcemerritt/Library/Android/sdk/tools:/Users/pearcemerritt/Library/Android/sdk/tools/bin:/Users/pearcemerritt/Library/Android/sdk/platform-tools
9 verbose lifecycle jzz-midi-smf@1.2.4~coverage: CWD: /Users/pearcemerritt/dev/JZZ-midi-SMF
10 silly lifecycle jzz-midi-smf@1.2.4~coverage: Args: [ '-c', 'nyc report --reporter=text-lcov | coveralls' ]
11 silly lifecycle jzz-midi-smf@1.2.4~coverage: Returned: code: 1  signal: null
12 info lifecycle jzz-midi-smf@1.2.4~coverage: Failed to exec coverage script
13 verbose stack Error: jzz-midi-smf@1.2.4 coverage: `nyc report --reporter=text-lcov | coveralls`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1000:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
14 verbose pkgid jzz-midi-smf@1.2.4
15 verbose cwd /Users/pearcemerritt/dev/JZZ-midi-SMF
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/bin/npm" "run" "coverage"
18 verbose node v12.1.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error jzz-midi-smf@1.2.4 coverage: `nyc report --reporter=text-lcov | coveralls`
22 error Exit status 1
23 error Failed at the jzz-midi-smf@1.2.4 coverage script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jazz-soft** [comment]
Hi! Thank you for the notice!
The "coverage" script is not intended for manual run.
It is called by Travis-CI to report the testing results to coveralls.io.
(You can see both "build" and "coverage" badges on the RERADME page)
There is probably a Travis-CI security token missing when you are trying to run the script manually.
But that is not a problem at all!
:)

**Comment by pearcemerritt** [comment]
ah, gotcha, thanks for the response :)
